### ISSUE TITLE
Inconsistent Navbar buttons across pages 

### ISSUE THREAD

**Issue by rootCircle** [rootCircle/refdocs.io#3]
Navbar buttons are inconsistent in behavior and appearance across pages. Fixing it will require a consistent aesthetic looking design nav looking similar for all pages.

### Below are example from some of the pages
<details open>
<summary>Nav in Search Page</summary>
<img src="https://github.com/rootCircle/refdocs.io/assets/35325046/189943bb-6e24-459b-9985-f91d35f90dd7" alt="Search Page">
</details>

<details>
<summary>Nav in Homepage</summary>
<img src="https://github.com/rootCircle/refdocs.io/assets/35325046/9e56e328-5577-42c3-b8ae-1c548b0672ec" alt="Homepage">
</details>

<details>
<summary>Nav in About Page</summary>
<img src="https://github.com/rootCircle/refdocs.io/assets/35325046/e8c9dfe4-8197-463e-8d94-11ebc4e150b7" alt="About Page">

</details>

**Comment by KarthikAkshaj** [comment]
Assign me

**Comment by rootCircle** [comment]
Assigned :+1:
